apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/kt-cloudnative/vue_crud_security
        imagePullPolicy: Always
        env:
          - name: BACKEND_API_URL
            value: "http://backend" 
        ports:
        - containerPort: 80
