apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: ghcr.io/kt-cloudnative/vue_crud_security
  newTag: "20240206233917"
- name: ghcr.io/ujeongeom/vue_crud_security
  newTag: "20240215050301"
